config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "vacancies#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :vacancies, only: :index do
    resources :users, only: [:show], shallow: true do
      get 'download_resume', on: :member
    end
    get 'archived', on: :collection
  end

  resources :users, only: [] do
    controller "users/emails" do
      get 'new_email', on: :member,  as: 'new_email'
      post 'send_denial', on: :member
    end
  end
  resource :chart, controller: "vacancies/charts", only: [:show, :create]
  resources :invite_codes, only: [:index, :create]
  resources :companies, only: [:show, :edit, :update] do
    resources :vacancies, except: :index, shallow: true do
      post 'close', on: :member
      post 'attach_resume', on: :member
    end
    resources :build, controller: 'companies/build', only: [:show, :update]
  end
  resource :job_list, only: :show
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  include RailsAdminCharts
  validates :title, :description, :deadline, :city, :country, presence: true
  belongs_to :company
  belongs_to :speciality
  has_many :applied_jobs
  has_many :users, :through => :applied_jobs
  before_validation :set_city_and_country

  default_scope -> {where("deadline > ?", Date.current)}
  scope :archived, -> {unscoped.where("deadline < ?", Date.current)}

  def attach_resume user, resume_file
    unless user.vacancies.exists? self.id
      user.resume.store! resume_file
      user.save!
      user.vacancies << self
    end
  end

  def allow_to_close? user
    user &&
    if user.role? :employer
      self.company.user_id == user.id
    elsif user.role? :manager
      self.company.user_id == user.get_owner_of_invite_code.id
    else
      false
    end
  end
  def close
    self.update deadline: (Date.current - 1)
  end

  def can_applly? user
    user &&
    self.deadline > Date.current &&
    user.role?(:applicant) &&
    !self.users.exists?(user.id)
  end

  def set_city_and_country
    self.city = self.company.city
    self.country = self.company.country
  end


  def self.class_for_condition
    Company
  end

  def self.chart_form?
    true
  end

  def self.sym_for_condition
    :company_id
  end

end

app/controllers/vacancies/charts_controller.rb
class Vacancies::ChartsController < ApplicationController

  authorize_resource :class => false

  def create
    @chart_form = ChartForm.new(params: params["chart_form"])
    @chart_data = @chart_form.graph_data
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  def show
    @chart_form = ChartForm.new
  end

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController

  load_and_authorize_resource :company, :except => [:index, :show, :attach_resume, :archived]
  load_and_authorize_resource :vacancy, :through => :company, :except => [:index, :show, :attach_resume, :archived]
  before_action :specialities, except: [:create, :update, :destroy]

  def index
    @search = VacancySearch.new(params: params)
    @vacancies = @search.call.page(params[:page])
  end

  def show
    @vacancy = unscoped_vacancies.find(params[:id])
  end


  def new
  end

  def archived
    @vacancies = Vacancy.archived.page(params[:page])
  end

  def create
    if @vacancy.save
      redirect_to @vacancy, notice: 'Vacancy was successfully created.'
    else
      render :new
    end
  end

  def close
    if @vacancy.close
      redirect_to :back, notice: "Vacancy is closed"
    else
      redirect_to :back, alert: "Something is wrong. Vacancy is not closed"
    end
  end

  def attach_resume
    @vacancy = unscoped_vacancies.find(params[:id])
    authorize! :attach_resume, @vacancy
    if params[:vacancy][:file].present?
      @vacancy.attach_resume(current_user, params[:vacancy][:file])
      redirect_to @vacancy, notice: 'Your resumne was successfully sent.'
    else
      render :show
    end
  end

  private

  def unscoped_vacancies
    Vacancy.unscoped
  end
  def specialities
    @specialities = Speciality.all
  end
  def vacancy_params
    params.require(:vacancy).permit(:title, :description, :deadline, :company_id,
                                    :speciality_id, :city, :country, :file)
  end
end

app/views/vacancies/_form.haml
.col-md-4.col-md-offset-3
  = form_for @vacancy, url: company_vacancies_path(:company_id => @vacancy.company.id)do |f|
    = render partial: "shared/error_messages", locals: {object: @vacancy}
    .form-group
      = f.label "Title"
      %br/
      .input-group
        = f.text_field :title, class: "form-control", placeholder: "Title"
        %span.input-group-addon
          %span.glyphicon.glyphicon-asterisk
      = f.label "Deadline"
      %br/
      = f.date_field :deadline, min: Date.today, class: "form-control", placeholder: "Deadline"
      = f.label "Speciality"
      %br/
      =f.select :speciality_id, Speciality.all.collect{|s| [ s.name, s.id ] }, {prompt: "Choose a speciality"}, {class: "form-control"}
      = f.label "Description"
      %br/
      .input-group
        = f.text_area :description, rows: 10, class: "form-control"
        %span.input-group-addon
          %span.glyphicon.glyphicon-asterisk
      %br/
      = f.submit "Submit", class: "btn btn-primary"

app/views/vacancies/archived.haml
.col-sm-6.col-md-5.col-md-offset-2
  %h1.col-md-offset-2 Archived Listing Jobs
  = render partial: "shared/list_jobs", locals: {vacancies: @vacancies}
  .col-md-8.col-md-offset-3
    = paginate @vacancies
= render partial: 'shared/specialities', locals: {specialities: @specialities}

app/views/vacancies/index.haml
.col-sm-6.col-md-5.col-md-offset-2
  %h1.col-md-offset-2 Listing Jobs
  = render partial: "shared/list_jobs", locals: {vacancies: @vacancies}
  .col-md-8.col-md-offset-3
    = paginate @vacancies
= render partial: 'shared/specialities', locals: {specialities: @specialities}

app/views/vacancies/new.haml
.col-md-4.col-md-offset-3
  %h2
    New vacancy
= render 'form'

app/views/vacancies/show.haml
.col-sm-6.col-md-5.col-md-offset-2
  .row
    .panel.panel-info
      .panel-heading.col-md-12
        %span.pull-left{:style => "font-size: 30px"}
          = @vacancy.title.humanize
        %span.pull-right
          %b.text-danger #{@vacancy.deadline}
        %br
        .clearfix
        .col-md-4
          %b Country:
          = link_to CS.countries[@vacancy.country.upcase.to_sym], vacancies_path(:country => @vacancy.country)
        .col-md-4
          %b City:
          = link_to @vacancy.city, vacancies_path(:city => @vacancy.city)
        .col-md-4
          %b Company:
          = link_to @vacancy.company.name, vacancies_path(:company_id => @vacancy.company.id)
      .panel-body
        = @vacancy.description
        - if user_signed_in? && @vacancy.users.any? && current_user.current?(@vacancy.company.user_id)
          %br/
          %h2.col-md-offset-3 Applied resumes
          %table.table
            %thead
              %tr
                %th #
                %th First Name
                %th Last Name
                %th Resume
                %th Send email of denial
            %tbody
            - @vacancy.users.each.with_index do |user, i|
              %tr
                %th #{i + 1}
                %td #{user.first_name}
                %td #{user.last_name}
                %td{"data-no-turbolink" => ""}
                  = link_to "Download", download_resume_user_path(user, vacancy_id: @vacancy)
                %td
                  = link_to "Send or Edit email", new_email_user_path(user), remote: true
        #denial_email
      .panel-footer
        - if @vacancy.can_applly?(current_user)
          = form_tag attach_resume_vacancy_path, class: "navbar-form", multipart: true do
            .form-group
              = file_field_tag "vacancy[file]", class: "form-control"
            = submit_tag "Send resume", class: "btn btn-default"
        -else
          .alert.alert-warning.fade.in
            You don't have rights to apply your resume

= render partial: 'shared/specialities', locals: {specialities: @specialities}