config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "vacancies#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :vacancies, only: :index do
    resources :users, only: [:show], shallow: true do
      get 'download_resume', on: :member
    end
    get 'archived', on: :collection
  end

  resources :users, only: [] do
    controller "users/emails" do
      get 'new_email', on: :member,  as: 'new_email'
      post 'send_denial', on: :member
    end
  end
  resource :chart, controller: "vacancies/charts", only: [:show, :create]
  resources :invite_codes, only: [:index, :create]
  resources :companies, only: [:show, :edit, :update] do
    resources :vacancies, except: :index, shallow: true do
      post 'close', on: :member
      post 'attach_resume', on: :member
    end
    resources :build, controller: 'companies/build', only: [:show, :update]
  end
  resource :job_list, only: :show
end

app/models/company.rb
class Company < ActiveRecord::Base

  validates :country,       presence: true, if: :active_or_country?
  validates :city,          presence: true, if: :active_or_city?
  validates :name,          presence: true, if: :active_or_info?
  validates :description,   presence: true, if: :active_or_info?

  belongs_to :user
  has_many :vacancies


  def active?
    status == 'active'
  end

  def active_or_country?
    status.include?('country') || active?
  end

  def active_or_city?
    status.include?('city') || active?
  end

  def active_or_info?
    status.include?('info') || active?
  end
end

app/controllers/companies/build_controller.rb
class Companies::BuildController < ApplicationController

  include Wicked::Wizard
  steps :add_country, :add_city, :add_info
  before_action :set_company

  def show
    render_wizard
  end

  def update
    params[:company][:status] = step.to_s
    params[:company][:status] = 'active' if step == steps.last
    @company.update(company_params)
    render_wizard @company
  end

  private
  def finish_wizard_path
    flash[:notice] = "Your company registered. After approving your account administrator you can sign in and post vacancies!"
    super
  end

  def company_params
    params.require(:company).permit(:name, :country, :city, :description, :url, :state, :status)
  end

  def set_company
    @company = Company.find(params[:company_id])
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  load_and_authorize_resource
  def show
    @vacancies = @company.vacancies.page(params[:page])
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: "Information about company was successfully updated"
    else
      render :edit
    end
  end

  private
  def company_params
    params.require(:company).permit(:name, :description, :country, :state, :city, :url, :status)
  end
end

app/views/companies/edit.haml
.col-md-4.col-md-offset-3
  = simple_form_for @company, url: company_path(@company) do |f|
    = f.input :country, collection: CountryStateSelect.countries_collection, input_html: {"data-placeholder" => "Choose a country..."}, label: false
    = f.input :state, CountryStateSelect.state_options({ form: f, field_names: { :country => :country, :state => :state}, input_html: {"data-placeholder" => "Choose a state..."}, label: false})
    = f.input :city, CountryStateSelect.city_options({form: f, field_names: {:state => :state, :city => :city}, input_html: {"data-placeholder" => "Choose a city..."}, label: false})
    .input-group
      = f.input_field :name, label: false, class: "form-control"
      %span.input-group-addon
        %span.glyphicon.glyphicon-asterisk
    %br
    .input-group
      = f.input_field :description, as: :text, label: false, class: "form-control"
      %span.input-group-addon
        %span.glyphicon.glyphicon-asterisk
    %br
    .input-group
      = f.input_field :url, as: :url, label: false, class: "form-control"
      %span.input-group-addon
        %span.glyphicon.glyphicon-asterisk
    = f.input_field :status, as: :hidden, value: "active"
    %br
    = f.button :submit, "Update company", class: "btn btn-primary btn-sm pull-right"

app/views/companies/show.haml
.col-sm-6.col-md-5.col-md-offset-2
  .col-md-offset-2
    %span.pull-right
      = link_to edit_company_path(@company) do
        .glyphicon.glyphicon-pencil.text-danger
    %h1 #{@company.name}
    %p #{@company.description}

  - @vacancies.each do |vacancy|
    .panel.panel-info
      .panel-heading.col-md-12
        .panel-title
        %span.pull-left{:style => "font-size: 30px"}
          = link_to vacancy.title.humanize, vacancy
        - if vacancy.allow_to_close? current_user
          = link_to close_vacancy_path(vacancy, company_id: vacancy.company_id), method: :post do
            %span.pull-right.glyphicon.glyphicon-remove
        %span.pull-right{:style => "margin: 0 30px"}
          %b.text-danger #{vacancy.deadline}
        %br
        .clearfix
        .col-md-4
          %b Country:
          = link_to CS.countries[vacancy.country.upcase.to_sym], vacancies_path(:country => vacancy.country)
        .col-md-4
          %b City:
          = link_to vacancy.city, vacancies_path(:city => vacancy.city)
        .col-md-4
          %b Company:
          = link_to vacancy.company.name, @company
      .panel-body
  .col-md-8.col-md-offset-3
    = paginate @vacancies