config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "vacancies#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :vacancies, only: :index do
    resources :users, only: [:show], shallow: true do
      get 'download_resume', on: :member
    end
    get 'archived', on: :collection
  end

  resources :users, only: [] do
    controller "users/emails" do
      get 'new_email', on: :member,  as: 'new_email'
      post 'send_denial', on: :member
    end
  end
  resource :chart, controller: "vacancies/charts", only: [:show, :create]
  resources :invite_codes, only: [:index, :create]
  resources :companies, only: [:show, :edit, :update] do
    resources :vacancies, except: :index, shallow: true do
      post 'close', on: :member
      post 'attach_resume', on: :member
    end
    resources :build, controller: 'companies/build', only: [:show, :update]
  end
  resource :job_list, only: :show
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title The Job Find
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "https://code.highcharts.com/highcharts.js", "chartkick"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %span.navbar-brand The Job Find
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{:class => active_class(root_path)}
              = link_to "Home", root_path
            %li{:class => active_class(archived_vacancies_path)}
              = link_to "Archived Jobs", archived_vacancies_path
            %li
              = form_tag vacancies_path, method: :get, class: "navbar-form" do
                .form-group
                  = text_field_tag :search, params[:search], class: "form-control", placeholder: "Search"
                = submit_tag "Search", class: "btn btn-default"
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li.navbar-text
                %b Hello, #{current_user.role.to_s.humanize}!
              - case
              - when current_user.role?(:admin)
                %li
                  = link_to "Admin panel", rails_admin_path
                %li
                  =link_to "Chart", chart_path
              - when current_user.role?(:employer)
                %li
                  = link_to "My profile", user_path(current_user)
                %li
                  = link_to "Invite codes", invite_codes_path
                %li
                  = link_to "My company", company_path(current_user.company)
                %li
                  = link_to "Post a vacancy", new_company_vacancy_path(:company_id => current_user.company.id)
              - when current_user.role?(:manager)
                %li
                  = link_to "My profile", user_path(current_user)
                %li
                  = link_to "My company", company_path(current_user.get_owner_of_invite_code.company)
                %li
                  = link_to "Post a vacancy", new_company_vacancy_path(:company_id => current_user.get_owner_of_invite_code.company.id)
              - else
                %li
                  = link_to "My profile", user_path(current_user)
                %li{:class => active_class(job_list_path)}
                  = link_to "Job List", job_list_path
              %li{:class => active_class(edit_user_registration_path(current_user))}
                = link_to "Settings", edit_user_registration_path(current_user)
              %li= link_to "Sign Out!", destroy_user_session_path, :method => :delete
            - else
              %li{:class => active_class(new_user_session_path)}
                = link_to "Sign In", new_user_session_path
              %li{:class => active_class(new_user_registration_path)}
                = link_to "Sign Up", new_user_registration_path
    .container-fluid
      .row
        .col-md-4.col-md-offset-3
          = render partial: "shared/flash_messages", flash: flash
        .col-md-12#main_content
          = yield